refatorando rotas
sad-ufcg/angular-ui pull request #10
Opened 2017-11-07 12:28 UTC by ArthurSampaio

Refatorei as rotas para poder suportar o lado do admin e do aluno. Poucas mudanças substanciais foram realizadas.

2017-11-17 22:03 UTC, hereismari approved these changes
Por mim ta ok!

2017-11-17 22:06 UTC, hereismari requested changes
Checa só os comentários que fiz, em geral ta ok :+1:

2017-11-17 22:06 UTC, mari-linhares commented on app/js/controller/cadastraTurmas.ctrl.js
> +            console.log(cadastraTurmasCtrl.files);
Mesmo.

2017-11-17 22:06 UTC, mari-linhares commented on app/js/component/sad-question-card-footer/sad-question-card-footer.component.js
> +            console.log(questionFooterCtrl.radioQuestion);
Console log é necessário? Ou um debug que não foi apagado?

2017-11-17 22:06 UTC, mari-linhares commented on app/js/component/sad-question-card/sad-question-card.component.js
> +            console.log(questionCardCtrl.radioQuestion);
Mesmo.

2017-11-17 22:06 UTC, mari-linhares commented on app/js/controller/admin.ctrl.js
> +			console.log(state);
Mesmo.

2017-11-17 22:06 UTC, mari-linhares commented on app/js/services/answer.srv.js
> +            console.log(questionnaire);
Mesmo.

2017-11-17 22:19 UTC, antunesdantass commented on app/js/component/sad-question-card-footer/sad-question-card-footer.component.js
> +        var questionFooterCtrl = this;
Por que usar o nome do questionário como nome da variável que guarda o contexto? O padrão self = this é mais conhecido, e compacto hauahauha

2017-11-17 22:19 UTC, antunesdantass commented on app/js/component/sad-question-card-footer/sad-question-card-footer.component.js
> +            console.log(questionFooterCtrl.radioQuestion);
remover o log

2017-11-17 22:19 UTC, antunesdantass commented on app/js/component/sad-question-card/sad-question-card.component.html
> +                                    <md-radio-button value="1"> 1&nbsp;&nbsp;&nbsp;&nbsp; </md-radio-button>
o que sao esses nbsp? so curiosidade mim

2017-11-17 22:19 UTC, antunesdantass commented on app/js/component/sad-question-card/sad-question-card.component.html
> +                                    <md-radio-button value="1"> 1&nbsp;&nbsp;&nbsp;&nbsp; </md-radio-button>
Por que não usa um ng-repeat aqui? ficaria mais compacto...

2017-11-17 22:19 UTC, antunesdantass commented on app/js/component/sad-question-card/sad-question-card.component.js
> +        var questionCardCtrl = this;
mim coisa pro this

2017-11-17 22:19 UTC, antunesdantass commented on app/js/component/sad-question-card/sad-question-card.component.js
> +            console.log(questionCardCtrl.radioQuestion);
Reforço o console.log

2017-11-17 22:19 UTC, antunesdantass commented on app/js/controller/admin.ctrl.js
> +		var adminCtrl = this;
Mesma coisa pro this

2017-11-17 22:19 UTC, antunesdantass commented on app/js/controller/cadastraTurmas.ctrl.js
> +        var cadastraTurmasCtrl = this;
Mesma coisa pro this

2017-11-17 22:19 UTC, antunesdantass commented on app/view/dashboard-admin.html
> +
Mulher tira isso socorro

2017-11-17 22:24 UTC, mari-linhares commented
Ah, outra coisa, o código deve ser prioritariamente em português.

2017-11-19 14:11 UTC, ArthurSampaio commented on app/js/component/sad-question-card/sad-question-card.component.html
> +                                    <md-radio-button value="1"> 1&nbsp;&nbsp;&nbsp;&nbsp; </md-radio-button>
&nbsp; são espaços em branco no html.

2017-11-19 14:33 UTC, merged