visualizar questionários aplicados
sad-ufcg/angular-ui pull request #33
Opened 2018-01-22 18:10 UTC by ArthurSampaio

Visualizar e enviar questionarios aplicados

2018-01-23 11:22 UTC, hereismari requested changes

2018-01-23 11:22 UTC, mari-linhares commented on app/js/factory/QuestionarioAplicado.js
> +                console.log(this._data);
Remover log?

2018-01-23 11:22 UTC, mari-linhares commented on app/js/controller/questionariosAplicados.ctrl.js
> +                    console.log(response);
Remover log?

2018-01-23 11:22 UTC, mari-linhares commented on app/js/controller/questionariosAplicados.ctrl.js
> +                    console.log(response);
Remover log?

2018-01-23 11:22 UTC, mari-linhares commented on app/js/controller/questionariosAplicados.ctrl.js
> +                    console.log(error);
Remover log?

2018-01-23 11:22 UTC, mari-linhares commented on app/js/services/aplicarQuestionario.srv.js
> +            console.log(questionario);
Remover log?

2018-01-23 11:22 UTC, mari-linhares commented on app/js/services/aplicarQuestionario.srv.js
> +                console.log(questionarioAplicado);
Remover log?

2018-01-23 11:22 UTC, mari-linhares commented on app/js/services/email.srv.js
> +                    console.log(response);
Remover log?

2018-01-23 11:22 UTC, mari-linhares commented on app/js/services/email.srv.js
> +                    console.log(response);
Remover log?

2018-01-25 03:07 UTC, ArthurSampaio commented on app/js/controller/questionariosAplicados.ctrl.js
> +                    console.log(response);
Feito!

2018-01-25 03:08 UTC, ArthurSampaio commented on app/js/controller/questionariosAplicados.ctrl.js
> +                    console.log(response);
Feito!

2018-01-25 03:08 UTC, ArthurSampaio commented on app/js/controller/questionariosAplicados.ctrl.js
> +                    console.log(error);
Feito!

2018-01-25 03:08 UTC, ArthurSampaio commented on app/js/services/aplicarQuestionario.srv.js
> +            console.log(questionario);
Feito!

2018-01-25 03:08 UTC, ArthurSampaio commented on app/js/factory/QuestionarioAplicado.js
> +                console.log(this._data);
Feito!

2018-01-25 03:08 UTC, ArthurSampaio commented on app/js/services/email.srv.js
> +                    console.log(response);
Feito!

2018-01-25 03:08 UTC, ArthurSampaio commented on app/js/services/email.srv.js
> +                    console.log(response);
Feito!

2018-01-25 11:29 UTC, hereismari approved these changes

2018-01-25 11:29 UTC, merged